name: fresensi
version: 1.0.0
publish_to: none
description: Presence apps integrate with Geo Location
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: 2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  flutter_svg: ^2.0.5
  map_launcher: ^2.5.0+1
  geolocator: ^9.0.2
  maps_launcher: ^2.2.0
  intl: ^0.17.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

